AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: NETEC Course Generator with YAML Structure Integration
Parameters:
  ECRRepository:
    Type: String
    Default: crewai-course-generator
    Description: ECR repository name
  AccountId:
    Type: String
    Default: '746434296869'
    Description: AWS Account ID
Globals:
  Api:
    Cors:
      AllowMethods: "'OPTIONS,GET,POST,PUT,DELETE'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,x-amz-content-sha256'"
      AllowOrigin: "'*'"
    Auth:
      ApiKeyRequired: false
      DefaultAuthorizer: AWS_IAM
    GatewayResponses:
      UNAUTHORIZED:
        StatusCode: 403
        ResponseParameters:
          Headers:
            Access-Control-Allow-Origin: "'*'"
            Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,x-amz-content-sha256'"
            Access-Control-Allow-Methods: "'OPTIONS,GET,POST,PUT,DELETE'"
      MISSING_AUTHENTICATION_TOKEN:
        StatusCode: 403
        ResponseParameters:
          Headers:
            Access-Control-Allow-Origin: "'*'"
            Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,x-amz-content-sha256'"
            Access-Control-Allow-Methods: "'OPTIONS,GET,POST,PUT,DELETE'"
      ACCESS_DENIED:
        StatusCode: 403
        ResponseParameters:
          Headers:
            Access-Control-Allow-Origin: "'*'"
            Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,x-amz-content-sha256'"
            Access-Control-Allow-Methods: "'OPTIONS,GET,POST,PUT,DELETE'"
      INVALID_SIGNATURE:
        StatusCode: 403
        ResponseParameters:
          Headers:
            Access-Control-Allow-Origin: "'*'"
            Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,x-amz-content-sha256'"
            Access-Control-Allow-Methods: "'OPTIONS,GET,POST,PUT,DELETE'"
      DEFAULT_5XX:
        StatusCode: 500
        ResponseParameters:
          Headers:
            Access-Control-Allow-Origin: "'*'"
            Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,x-amz-content-sha256'"
            Access-Control-Allow-Methods: "'OPTIONS,GET,POST,PUT,DELETE'"
Resources:
  CrewaiContentGen:
    Type: AWS::Serverless::Function
    Properties:
      Description: Generates structured course content following YAML outline requirements
      PackageType: Image
      ImageUri: crewai-course_gen:latest
      ImageConfig:
        Command:
        - content_gen.lambda_handler
      Environment:
        Variables:
          OUTPUT_S3_BUCKET: crewai-course-artifacts
          BEDROCK_API_KEY: ABSKSnVhbkRhdmlkLWF0LTc0NjQzNDI5Njg2OTpLRjhMV0Erd2tjVDhKRmllbXVtbysyRnN1MHVoeXpzWWoveFYvOWpwS1UvTTBDbXN6Mk0xV001UzN2ND0=
          YAML_STRUCTURE_ENABLED: 'true'
      Timeout: 900
      MemorySize: 2048
      Architectures:
      - x86_64
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - bedrock:InvokeModel
          - bedrock:InvokeModelWithResponseStream
          Resource: '*'
        - Effect: Allow
          Action:
          - s3:GetObject
          - s3:PutObject
          - s3:PutObjectAcl
          - s3:ListBucket
          Resource:
          - arn:aws:s3:::crewai-course-artifacts
          - arn:aws:s3:::crewai-course-artifacts/*
          - arn:aws:s3:::netec-course-generator-content
          - arn:aws:s3:::netec-course-generator-content/*
    Metadata:
      DockerContext: /home/juan/netec-cg
      DockerTag: latest
      Dockerfile: Dockerfile
      SamResourceId: CrewaiContentGen
  CrewaiVisualPlanner:
    Type: AWS::Serverless::Function
    Properties:
      Description: Generates visual planning prompts from course content
      PackageType: Image
      ImageUri: crewai-course_gen:latest
      ImageConfig:
        Command:
        - visual_planner.lambda_handler
      Environment:
        Variables:
          OUTPUT_S3_BUCKET: crewai-course-artifacts
          BEDROCK_API_KEY: ABSKSnVhbkRhdmlkLWF0LTc0NjQzNDI5Njg2OTpLRjhMV0Erd2tjVDhKRmllbXVtbysyRnN1MHVoeXpzWWoveFYvOWpwS1UvTTBDbXN6Mk0xV001UzN2ND0=
          YAML_STRUCTURE_ENABLED: 'true'
      Timeout: 900
      MemorySize: 2048
      Architectures:
      - x86_64
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - bedrock:InvokeModel
          - bedrock:InvokeModelWithResponseStream
          Resource: '*'
        - Effect: Allow
          Action:
          - s3:GetObject
          - s3:PutObject
          - s3:PutObjectAcl
          - s3:ListBucket
          Resource:
          - arn:aws:s3:::crewai-course-artifacts
          - arn:aws:s3:::crewai-course-artifacts/*
          - arn:aws:s3:::netec-course-generator-content
          - arn:aws:s3:::netec-course-generator-content/*
    Metadata:
      DockerContext: /home/juan/netec-cg
      DockerTag: latest
      Dockerfile: Dockerfile
      SamResourceId: CrewaiVisualPlanner
  CrewaiImagesGen:
    Type: AWS::Serverless::Function
    Properties:
      Description: Generates images from visual prompts using Google Gemini
      PackageType: Image
      ImageUri: crewai-course_gen:latest
      ImageConfig:
        Command:
        - images_gen.lambda_handler
      Environment:
        Variables:
          OUTPUT_S3_BUCKET: crewai-course-artifacts
          YAML_STRUCTURE_ENABLED: 'true'
      Timeout: 900
      MemorySize: 2048
      Architectures:
      - x86_64
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - s3:GetObject
          - s3:PutObject
          - s3:PutObjectAcl
          - s3:ListBucket
          Resource:
          - arn:aws:s3:::crewai-course-artifacts
          - arn:aws:s3:::crewai-course-artifacts/*
          - arn:aws:s3:::netec-course-generator-content
          - arn:aws:s3:::netec-course-generator-content/*
    Metadata:
      DockerContext: /home/juan/netec-cg
      DockerTag: latest
      Dockerfile: Dockerfile
      SamResourceId: CrewaiImagesGen
  BookBuilder:
    Type: AWS::Serverless::Function
    Properties:
      Description: Builds complete books by combining lessons and images
      Handler: book_builder.lambda_handler
      Runtime: python3.12
      CodeUri: lambda/
      MemorySize: 512
      Timeout: 300
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
            - s3:PutObjectAcl
            - s3:ListBucket
          Resource:
          - arn:aws:s3:::crewai-course-artifacts
          - arn:aws:s3:::crewai-course-artifacts/*
          - arn:aws:s3:::netec-course-generator-content
          - arn:aws:s3:::netec-course-generator-content/*
      Events:
        BuildBookApi:
          Type: Api
          Properties:
            Path: /build-book
            Method: post
    Metadata:
      SamResourceId: BookBuilder
  ListProjectsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Lists available course projects for the Book Builder interface
      Handler: list_projects.lambda_handler
      Runtime: python3.12
      CodeUri: lambda/
      MemorySize: 256
      Timeout: 30
      Environment:
        Variables:
          COURSE_BUCKET: crewai-course-artifacts
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:ListBucket
          Resource:
          - arn:aws:s3:::crewai-course-artifacts
          - arn:aws:s3:::crewai-course-artifacts/*
          - arn:aws:s3:::netec-course-generator-content
          - arn:aws:s3:::netec-course-generator-content/*
      Events:
        ListProjectsApi:
          Type: Api
          Properties:
            Path: /list-projects
            Method: get
  LoadBookFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Loads book data for the Book Editor interface
      Handler: load_book.lambda_handler
      Runtime: python3.12
      CodeUri: lambda/
      MemorySize: 256
      Timeout: 30
      Environment:
        Variables:
          COURSE_BUCKET: crewai-course-artifacts
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
            - s3:GetObject
          Resource:
          - arn:aws:s3:::crewai-course-artifacts
          - arn:aws:s3:::crewai-course-artifacts/*
          - arn:aws:s3:::netec-course-generator-content
          - arn:aws:s3:::netec-course-generator-content/*
      Events:
        LoadBookApi:
          Type: Api
          Properties:
            Path: /load-book/{projectFolder}
            Method: get
  SaveBookFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Saves book data from the Book Editor interface
      Handler: save_book.lambda_handler
      Runtime: python3.12
      CodeUri: lambda/
      MemorySize: 256
      Timeout: 30
      Environment:
        Variables:
          COURSE_BUCKET: crewai-course-artifacts
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
            - s3:PutObject
          Resource:
          - arn:aws:s3:::crewai-course-artifacts
          - arn:aws:s3:::crewai-course-artifacts/*
          - arn:aws:s3:::netec-course-generator-content
          - arn:aws:s3:::netec-course-generator-content/*
      Events:
        SaveBookApi:
          Type: Api
          Properties:
            Path: /save-book
            Method: post
  # CORS Handler for OPTIONS requests
  CorsHandler:
    Type: AWS::Serverless::Function
    Properties:
      Description: Handles CORS preflight OPTIONS requests
      Handler: cors_handler.lambda_handler
      Runtime: python3.12
      CodeUri: lambda/
      MemorySize: 128
      Timeout: 5
      Events:
        StartJobOptions:
          Type: Api
          Properties:
            Path: /start-job
            Method: options
            Auth:
              Authorizer: NONE
        ExecStatusOptions:
          Type: Api
          Properties:
            Path: /exec-status/{executionArn}
            Method: options
            Auth:
              Authorizer: NONE
  # Starter API - starts Step Functions execution
  StarterApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: API endpoint to start the ContentGen -> VisualPlanner state machine
      Handler: starter_api.lambda_handler
      Runtime: python3.12
      CodeUri: lambda/
      MemorySize: 256
      Timeout: 30
      Environment:
        Variables:
          STATE_MACHINE_ARN: !Ref CourseGeneratorStateMachine
          SKIP_S3_HEAD_CHECK: 'true'
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - states:StartExecution
              Resource: !Ref CourseGeneratorStateMachine
            - Effect: Allow
              Action:
                - s3:HeadObject
              Resource:
                - arn:aws:s3:::crewai-course-artifacts/*
      Events:
        StartJobApi:
          Type: Api
          Properties:
            Path: /start-job
            Method: post
            Auth:
              Authorizer: NONE  # Temporarily disable IAM auth to test

  # Presign endpoint - issues presigned URLs for S3 uploads
  PresignFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Issues presigned URLs for outline uploads
      Handler: presign.lambda_handler
      Runtime: python3.12
      CodeUri: lambda/
      MemorySize: 128
      Timeout: 10
      Environment:
        Variables:
          UPLOAD_BUCKET: crewai-course-artifacts
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
              Resource:
                - arn:aws:s3:::crewai-course-artifacts/uploads/*
      Events:
        PresignApi:
          Type: Api
          Properties:
            Path: /presign
            Method: post
            

  # Exec status endpoint - query Step Functions for execution status
  ExecStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Returns Step Functions execution status for a given arn
      Handler: exec_status.lambda_handler
      Runtime: python3.12
      CodeUri: lambda/
      MemorySize: 128
      Timeout: 10
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - states:DescribeExecution
                - states:GetExecutionHistory
              Resource: 
                - !Sub "arn:aws:states:${AWS::Region}:${AWS::AccountId}:execution:${CourseGeneratorStateMachine.Name}:*"
                - !Sub "arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:${CourseGeneratorStateMachine.Name}"
      Events:
        ExecStatusApi:
          Type: Api
          Properties:
            Path: /exec-status/{executionArn}
            Method: get
            Auth:
              Authorizer: NONE  # Temporarily disable IAM auth

  # Step Functions State Machine for Content Generation Workflow
  CourseGeneratorStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: CourseGeneratorStateMachine
      Definition:
        Comment: "Orchestrate ContentGen -> VisualPlanner -> ImagesGen for a single lesson"
        StartAt: InvokeContentGen
        States:
          InvokeContentGen:
            Type: Task
            Resource: arn:aws:states:::lambda:invoke
            Parameters:
              FunctionName: !GetAtt CrewaiContentGen.Arn
              Payload.$: "$"
            Retry:
              - ErrorEquals:
                  - Lambda.ServiceException
                  - Lambda.AWSLambdaException
                  - Lambda.SdkClientException
                IntervalSeconds: 5
                MaxAttempts: 2
                BackoffRate: 2.0
            Catch:
              - ErrorEquals:
                  - States.ALL
                ResultPath: $.error
                Next: FailState
            Next: ParseContentGenResult
          ParseContentGenResult:
            Type: Pass
            Parameters:
              lesson_key.$: $.Payload.lesson_key
              course_bucket.$: $.Payload.course_bucket
              project_folder.$: $.Payload.project_folder
              payload.$: $.Payload
              original.$: "$"
              model_provider: "bedrock"  # Default value
              performance_mode: "balanced"  # Default value
              content_source: "local"  # Default value
            Next: InvokeVisualPlanner
          InvokeVisualPlanner:
            Type: Task
            Resource: arn:aws:states:::lambda:invoke
            Parameters:
              FunctionName: !GetAtt CrewaiVisualPlanner.Arn
              Payload:
                course_bucket.$: $.course_bucket
                lesson_key.$: $.lesson_key
                project_folder.$: $.project_folder
                model_provider.$: $.model_provider
                performance_mode.$: $.performance_mode
                content_source.$: $.content_source
                original.$: "$"
            Retry:
              - ErrorEquals:
                  - Lambda.ServiceException
                  - Lambda.AWSLambdaException
                  - Lambda.SdkClientException
                IntervalSeconds: 5
                MaxAttempts: 2
                BackoffRate: 2.0
            Catch:
              - ErrorEquals:
                  - States.ALL
                ResultPath: $.error
                Next: FailState
            Next: InvokeImagesGen
          InvokeImagesGen:
            Type: Task
            Resource: arn:aws:states:::lambda:invoke
            Parameters:
              FunctionName: !GetAtt CrewaiImagesGen.Arn
              Payload:
                course_bucket.$: $.Payload.bucket
                project_folder.$: $.Payload.project_folder
                prompts_s3_prefix.$: $.Payload.prompts_s3_prefix
                max_images.$: $$.Execution.Input.max_images
                original.$: "$"
            Retry:
              - ErrorEquals:
                  - Lambda.ServiceException
                  - Lambda.AWSLambdaException
                  - Lambda.SdkClientException
                IntervalSeconds: 5
                MaxAttempts: 2
                BackoffRate: 2.0
            Catch:
              - ErrorEquals:
                  - States.ALL
                ResultPath: $.error
                Next: FailState
            Next: SuccessState
          FailState:
            Type: Fail
            Cause: TaskFailed
            Error: OrchestrationFailed
          SuccessState:
            Type: Succeed
      Type: STANDARD
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource:
                - !GetAtt CrewaiContentGen.Arn
                - !GetAtt CrewaiVisualPlanner.Arn
                - !GetAtt CrewaiImagesGen.Arn

Outputs:
  ContentGenerationFunction:
    Description: Content Generation Lambda Function ARN with YAML Structure Integration
    Value:
      Fn::GetAtt:
      - CrewaiContentGen
      - Arn
  VisualPlannerFunction:
    Description: Visual Planning Lambda Function ARN
    Value:
      Fn::GetAtt:
      - CrewaiVisualPlanner
      - Arn
  ImagesGenFunction:
    Description: Image Generation Lambda Function ARN
    Value:
      Fn::GetAtt:
      - CrewaiImagesGen
      - Arn
  BookBuilderFunction:
    Description: Book Builder Lambda Function ARN
    Value:
      Fn::GetAtt:
      - BookBuilder
      - Arn
  ListProjectsFunction:
    Description: List Projects Lambda Function ARN
    Value:
      Fn::GetAtt:
      - ListProjectsFunction
      - Arn
  LoadBookFunction:
    Description: Load Book Lambda Function ARN
    Value:
      Fn::GetAtt:
      - LoadBookFunction
      - Arn
  StarterApiFunction:
    Description: Starter API Lambda ARN
    Value:
      Fn::GetAtt:
      - StarterApiFunction
      - Arn
  PresignFunction:
    Description: Presign Lambda ARN
    Value:
      Fn::GetAtt:
      - PresignFunction
      - Arn
  ExecStatusFunction:
    Description: ExecStatus Lambda ARN
    Value:
      Fn::GetAtt:
      - ExecStatusFunction
      - Arn
  CourseGeneratorStateMachineArn:
    Description: Step Functions State Machine ARN
    Value: !Ref CourseGeneratorStateMachine
  ApiBaseUrl:
    Description: API Gateway base URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  PresignEndpoint:
    Description: Presign endpoint
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/presign"
  StartJobEndpoint:
    Description: Start job endpoint
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/start-job"
  ExecStatusEndpoint:
    Description: Execution status endpoint
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/exec-status"
